name: CICD
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Setup Go
        uses: actions/setup-go@v2 
        with:
          go-version: '1.14.0'
      - name: Install dependencies
        run: go mod download
      - name: Run vet
        run: go vet .
      - name: Run test
        run: go test .